name: umash_user
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  intl: ^0.18.1
  get: ^4.6.5
  http: ^1.1.0
  shimmer: ^2.0.0
  google_fonts: any
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_smart_dialog: ^4.5.5
  url_launcher: ^6.1.14
  flutter_html: any
  image_picker: ^1.0.7
  flutter_screenutil: ^5.9.0
  pin_code_fields: ^8.0.1
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Connectivity
  connectivity_plus: ^4.0.2

  # Firebase
  firebase_core: ^2.8.0
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  firebase_auth: ^4.14.1

  # Firebase Auth
  flutter_facebook_auth: ^6.1.1
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^5.0.0

  # Google Maps
  google_maps_place_picker_mb: ^3.0.1
  geolocator: ^10.1.1
  flutter_polyline_points: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/language/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
